import type { Club, ClubTier } from "@/lib/models/types";

type ClubSeed = Omit<
  Club,
  "id" | "appearances" | "titles" | "finals" | "lastQualifiedSeasonId"
>;

function makeClub(
  name: string,
  country: string,
  league: string,
  tier: ClubTier,
  rating: number,
  logo: string
): ClubSeed {
  return {
    name,
    country,
    league,
    tier,
    rating,
    attackRating: rating + 1,
    defenseRating: rating,
    midfieldRating: rating,
    goalkeeperRating: rating - 1,
    coefficient: rating * 1.9,
    logo,
  };
}

export const CLUB_POOL: ClubSeed[] = [
  makeClub("Real Madrid", "Spain", "La Liga", "elite", 95, "RMA"),
  makeClub("Barcelona", "Spain", "La Liga", "elite", 92, "BAR"),
  makeClub("Atletico Madrid", "Spain", "La Liga", "strong", 88, "ATM"),
  makeClub("Sevilla", "Spain", "La Liga", "contender", 81, "SEV"),
  makeClub("Real Sociedad", "Spain", "La Liga", "contender", 82, "RSO"),
  makeClub("Girona", "Spain", "La Liga", "contender", 80, "GIR"),
  makeClub("Athletic Club", "Spain", "La Liga", "strong", 84, "ATH"),
  makeClub("Villarreal", "Spain", "La Liga", "contender", 81, "VIL"),
  makeClub("Manchester City", "England", "Premier League", "elite", 94, "MCI"),
  makeClub("Liverpool", "England", "Premier League", "elite", 92, "LIV"),
  makeClub("Arsenal", "England", "Premier League", "elite", 91, "ARS"),
  makeClub("Chelsea", "England", "Premier League", "strong", 85, "CHE"),
  makeClub(
    "Manchester United",
    "England",
    "Premier League",
    "strong",
    84,
    "MUN"
  ),
  makeClub(
    "Tottenham Hotspur",
    "England",
    "Premier League",
    "contender",
    82,
    "TOT"
  ),
  makeClub(
    "Newcastle United",
    "England",
    "Premier League",
    "strong",
    84,
    "NEW"
  ),
  makeClub("Aston Villa", "England", "Premier League", "contender", 83, "AVL"),
  makeClub("Inter", "Italy", "Serie A", "elite", 91, "INT"),
  makeClub("Juventus", "Italy", "Serie A", "strong", 87, "JUV"),
  makeClub("Milan", "Italy", "Serie A", "strong", 86, "MIL"),
  makeClub("Napoli", "Italy", "Serie A", "strong", 85, "NAP"),
  makeClub("Atalanta", "Italy", "Serie A", "strong", 85, "ATA"),
  makeClub("Roma", "Italy", "Serie A", "contender", 82, "ROM"),
  makeClub("Lazio", "Italy", "Serie A", "contender", 81, "LAZ"),
  makeClub("Bologna", "Italy", "Serie A", "contender", 78, "BOL"),
  makeClub("Bayern Munich", "Germany", "Bundesliga", "elite", 93, "BAY"),
  makeClub("Borussia Dortmund", "Germany", "Bundesliga", "strong", 87, "BVB"),
  makeClub("Bayer Leverkusen", "Germany", "Bundesliga", "elite", 90, "B04"),
  makeClub("RB Leipzig", "Germany", "Bundesliga", "strong", 84, "RBL"),
  makeClub("Stuttgart", "Germany", "Bundesliga", "contender", 82, "STU"),
  makeClub(
    "Eintracht Frankfurt",
    "Germany",
    "Bundesliga",
    "contender",
    80,
    "SGE"
  ),
  makeClub("Wolfsburg", "Germany", "Bundesliga", "outsider", 77, "WOB"),
  makeClub("Freiburg", "Germany", "Bundesliga", "outsider", 77, "SCF"),
  makeClub("Paris Saint-Germain", "France", "Ligue 1", "elite", 90, "PSG"),
  makeClub("Marseille", "France", "Ligue 1", "strong", 82, "OM"),
  makeClub("Monaco", "France", "Ligue 1", "strong", 83, "MON"),
  makeClub("Lille", "France", "Ligue 1", "contender", 80, "LIL"),
  makeClub("Lyon", "France", "Ligue 1", "contender", 80, "OL"),
  makeClub("Nice", "France", "Ligue 1", "contender", 79, "NIC"),
  makeClub("Benfica", "Portugal", "Primeira Liga", "strong", 84, "BEN"),
  makeClub("Porto", "Portugal", "Primeira Liga", "strong", 84, "POR"),
  makeClub("Sporting CP", "Portugal", "Primeira Liga", "strong", 85, "SCP"),
  makeClub("Braga", "Portugal", "Primeira Liga", "contender", 79, "BRA"),
  makeClub("PSV", "Netherlands", "Eredivisie", "strong", 84, "PSV"),
  makeClub("Feyenoord", "Netherlands", "Eredivisie", "strong", 82, "FEY"),
  makeClub("Ajax", "Netherlands", "Eredivisie", "strong", 83, "AJX"),
  makeClub("AZ Alkmaar", "Netherlands", "Eredivisie", "contender", 78, "AZ"),
  makeClub("Club Brugge", "Belgium", "Pro League", "contender", 78, "BRU"),
  makeClub("Anderlecht", "Belgium", "Pro League", "contender", 77, "AND"),
  makeClub(
    "Union Saint-Gilloise",
    "Belgium",
    "Pro League",
    "outsider",
    76,
    "USG"
  ),
  makeClub("Genk", "Belgium", "Pro League", "outsider", 75, "GNK"),
  makeClub("Galatasaray", "Turkey", "Super Lig", "contender", 80, "GAL"),
  makeClub("Fenerbahce", "Turkey", "Super Lig", "contender", 80, "FEN"),
  makeClub("Besiktas", "Turkey", "Super Lig", "outsider", 76, "BES"),
  makeClub("Red Bull Salzburg", "Austria", "Bundesliga", "outsider", 75, "SAL"),
  makeClub("Sturm Graz", "Austria", "Bundesliga", "outsider", 73, "STG"),
  makeClub("Celtic", "Scotland", "Premiership", "contender", 78, "CEL"),
  makeClub("Rangers", "Scotland", "Premiership", "contender", 78, "RAN"),
  makeClub(
    "Shakhtar Donetsk",
    "Ukraine",
    "Premier League",
    "outsider",
    76,
    "SHA"
  ),
  makeClub("Dynamo Kyiv", "Ukraine", "Premier League", "outsider", 75, "DKY"),
  makeClub(
    "Sparta Prague",
    "Czech Republic",
    "First League",
    "outsider",
    75,
    "SPA"
  ),
  makeClub(
    "Slavia Prague",
    "Czech Republic",
    "First League",
    "outsider",
    75,
    "SLA"
  ),
  makeClub("Crvena Zvezda", "Serbia", "SuperLiga", "outsider", 74, "CZV"),
  makeClub("Partizan", "Serbia", "SuperLiga", "outsider", 71, "PAR"),
  makeClub("Dinamo Zagreb", "Croatia", "HNL", "outsider", 74, "DIN"),
  makeClub("Hajduk Split", "Croatia", "HNL", "outsider", 71, "HAJ"),
  makeClub("Olympiacos", "Greece", "Super League", "outsider", 77, "OLY"),
  makeClub("PAOK", "Greece", "Super League", "outsider", 75, "PAO"),
  makeClub("AEK Athens", "Greece", "Super League", "outsider", 74, "AEK"),
  makeClub("Young Boys", "Switzerland", "Super League", "outsider", 72, "YBO"),
  makeClub("Basel", "Switzerland", "Super League", "outsider", 71, "BAS"),
  makeClub("Ludogorets", "Bulgaria", "First League", "outsider", 70, "LUD"),
  makeClub("Dinamo Bucharest", "Romania", "SuperLiga", "outsider", 68, "DBU"),
  makeClub("Steaua Bucharest", "Romania", "SuperLiga", "outsider", 71, "FCS"),
  makeClub("Ferencvaros", "Hungary", "NB I", "outsider", 70, "FER"),
  makeClub(
    "Slovan Bratislava",
    "Slovakia",
    "Super Liga",
    "outsider",
    68,
    "SLO"
  ),
  makeClub("Molde", "Norway", "Eliteserien", "outsider", 71, "MOL"),
  makeClub("Bodo/Glimt", "Norway", "Eliteserien", "outsider", 72, "BOD"),
  makeClub("Midtjylland", "Denmark", "Superliga", "outsider", 71, "MID"),
  makeClub("Copenhagen", "Denmark", "Superliga", "outsider", 74, "FCK"),
];
