import type { TournamentStep } from '@/lib/models/types';

export const STEP_ORDER: TournamentStep[] = [
  'seasonGenerated',
  'leagueDraw',
  'leagueMatchday1',
  'leagueMatchday2',
  'leagueMatchday3',
  'leagueMatchday4',
  'leagueMatchday5',
  'leagueMatchday6',
  'leagueMatchday7',
  'leagueMatchday8',
  'finalLeagueTable',
  'playoffDraw',
  'playoffFirstLegs',
  'playoffSecondLegs',
  'ro16Draw',
  'ro16FirstLegs',
  'ro16SecondLegs',
  'quarterfinalFirstLegs',
  'quarterfinalSecondLegs',
  'semifinalFirstLegs',
  'semifinalSecondLegs',
  'final',
  'champion',
  'seasonHighlights',
];

export const STEP_LABELS: Record<TournamentStep, string> = {
  seasonGenerated: 'Season Generated',
  leagueDraw: 'League Draw',
  leagueMatchday1: 'League Matchday 1',
  leagueMatchday2: 'League Matchday 2',
  leagueMatchday3: 'League Matchday 3',
  leagueMatchday4: 'League Matchday 4',
  leagueMatchday5: 'League Matchday 5',
  leagueMatchday6: 'League Matchday 6',
  leagueMatchday7: 'League Matchday 7',
  leagueMatchday8: 'League Matchday 8',
  finalLeagueTable: 'Final League Table',
  playoffDraw: 'Playoff Draw',
  playoffFirstLegs: 'Playoff First Legs',
  playoffSecondLegs: 'Playoff Second Legs',
  ro16Draw: 'Round of 16 Draw',
  ro16FirstLegs: 'Round of 16 First Legs',
  ro16SecondLegs: 'Round of 16 Second Legs',
  quarterfinalFirstLegs: 'Quarterfinal First Legs',
  quarterfinalSecondLegs: 'Quarterfinal Second Legs',
  semifinalFirstLegs: 'Semifinal First Legs',
  semifinalSecondLegs: 'Semifinal Second Legs',
  final: 'Final',
  champion: 'Champion',
  seasonHighlights: 'Season Highlights',
};
